In [1]:
# from yahoo_fin.stock_info import get_data
# amazon_weekly= get_data("TCS", start_date="12/04/2009", end_date="12/04/2020", index_as_date = True, interval="1wk")
# amazon_weekly

In [2]:
import quandl
import numpy as np
import pandas as pd
import re

In [3]:
quandl.ApiConfig.api_key = "2At3atzXCrMx_BXfkyz7"

In [4]:
metadata = pd.read_csv('BSE_metadata.csv')
metadata.head()

,code,name,description,refreshed_at,from_date,to_date
0,BOM500002,ABB India Limited EOD Prices,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,1/18/2021
1,BOM500003,AEGIS LOGISTICS LTD. EOD Prices,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,1/18/2021
2,BOM500008,AMARA RAJA BATTERIES LTD. EOD Prices,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,1/18/2021
3,BOM500009,AMBALAL SARABHAI ENTERPRISES LTD. EOD Prices,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,1/18/2021
4,BOM500010,HOUSING DEVELOPMENT FINANCE CORP.LTD. EOD Prices,End of Day prices and additional trading infor...,1/19/2021 14:15,1/3/1992,1/18/2021

In [5]:
metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5120 entries, 0 to 5119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   code          5120 non-null   object
 1   name          5120 non-null   object
 2   description   5120 non-null   object
 3   refreshed_at  5009 non-null   object
 4   from_date     5009 non-null   object
 5   to_date       5009 non-null   object
dtypes: object(6)
memory usage: 240.1+ KB

In [6]:
metadata.shape

(5120, 6)

In [7]:
metadata['to_date']= pd.to_datetime(metadata['to_date'])

In [8]:
# metadata.loc[metadata['to_date'] == '1/13/2021']

In [9]:
metadata['to_date'].value_counts(dropna = False)

2021-01-19    2804
2021-01-18     442
NaT            111
2021-01-15      91
2021-01-14      59
              ...
2009-07-27       1
2099-12-24       1
2015-01-23       1
2019-05-31       1
2019-08-22       1
Name: to_date, Length: 781, dtype: int64

In [10]:
metadata = metadata.dropna()
metadata.shape

(5009, 6)

In [11]:
metadata['Year'] = metadata['to_date'].apply(lambda x:x.year)

In [12]:
metadata['name'] = metadata['name'].apply(lambda x:re.sub('EOD Prices', '', x))
metadata.head()

,code,name,description,refreshed_at,from_date,to_date,Year
0,BOM500002,ABB India Limited,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,2021-01-18,2021
1,BOM500003,AEGIS LOGISTICS LTD.,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,2021-01-18,2021
2,BOM500008,AMARA RAJA BATTERIES LTD.,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,2021-01-18,2021
3,BOM500009,AMBALAL SARABHAI ENTERPRISES LTD.,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,2021-01-18,2021
4,BOM500010,HOUSING DEVELOPMENT FINANCE CORP.LTD.,End of Day prices and additional trading infor...,1/19/2021 14:15,1/3/1992,2021-01-18,2021

In [13]:
# metadata.loc[metadata.Year.isnull()]

In [14]:
## get currently listed stocks
listedStocks = metadata.loc[metadata['Year'] == 2021]
listedStocks.reset_index(inplace=True)
print(listedStocks.shape)
listedStocks.head()

(3590, 8)

,index,code,name,description,refreshed_at,from_date,to_date,Year
0,0,BOM500002,ABB India Limited,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,2021-01-18,2021
1,1,BOM500003,AEGIS LOGISTICS LTD.,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,2021-01-18,2021
2,2,BOM500008,AMARA RAJA BATTERIES LTD.,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,2021-01-18,2021
3,3,BOM500009,AMBALAL SARABHAI ENTERPRISES LTD.,End of Day prices and additional trading infor...,1/19/2021 14:15,3/2/1992,2021-01-18,2021
4,4,BOM500010,HOUSING DEVELOPMENT FINANCE CORP.LTD.,End of Day prices and additional trading infor...,1/19/2021 14:15,1/3/1992,2021-01-18,2021

In [15]:
# get data for first record manually this helps in initalizing the df as well. 
code = f'BSE/{listedStocks.loc[0, "code"]}'
name = listedStocks.loc[0, 'name']
bsecode = code.replace('BOM', '')
print(code, name, bsecode)

BSE/BOM500002 ABB India Limited  BSE/500002

In [16]:
dataset = quandl.get(code, start_date='2000-01-01', end_date='2021-01-21').sort_values(by='Date', ascending=True)
dataset['StockName']=name
dataset['BSECode'] = bsecode

In [17]:
print(dataset.shape)
dataset.head()

(5240, 14)

,Open,High,Low,Close,WAP,No. of Shares,No. of Trades,Total Turnover,Deliverable Quantity,% Deli. Qty to Traded Qty,Spread H-L,Spread C-O,StockName,BSECode
Date,,,,,,,,,,,,,,
2000-01-03,259.0,269.95,259.00,269.95,263.710927,68014.0,697.0,17936035.0,NaN,NaN,10.95,10.95,ABB India Limited,BSE/500002
2000-01-04,274.5,277.00,261.00,263.00,266.326865,32466.0,356.0,8646568.0,NaN,NaN,16.00,-11.50,ABB India Limited,BSE/500002
2000-01-05,256.0,265.00,255.00,261.00,260.278473,24049.0,272.0,6259437.0,NaN,NaN,10.00,5.00,ABB India Limited,BSE/500002
2000-01-06,264.0,281.85,261.25,280.00,277.381874,91771.0,705.0,25455612.0,NaN,NaN,20.60,16.00,ABB India Limited,BSE/500002
2000-01-07,277.0,282.50,268.05,270.00,273.862386,58904.0,590.0,16131590.0,NaN,NaN,14.45,-7.00,ABB India Limited,BSE/500002

In [18]:
for i in range(1, len(listedStocks)):
    
    code = f'BSE/{listedStocks.loc[i, "code"]}'
    bsecode = code[7:]
    temp = quandl.get(code, start_date='2000-01-01', end_date='2021-03-16').sort_values(by='Date', ascending=True)
    temp['StockName']=listedStocks.loc[i, 'name']
    temp['BSECode'] = bsecode
    print(code, listedStocks.loc[i, 'name'], temp.shape)
    dataset = dataset.append(temp)
    print(dataset.shape)
    if i%10==0:
        dataset.to_csv('stocks.csv')

BSE/BOM500003 AEGIS LOGISTICS LTD.  (5191, 14)
(10431, 14)
BSE/BOM500008 AMARA RAJA BATTERIES LTD.  (5276, 14)
(15707, 14)
BSE/BOM500009 AMBALAL SARABHAI ENTERPRISES LTD.  (5229, 14)
(20936, 14)
BSE/BOM500010 HOUSING DEVELOPMENT FINANCE CORP.LTD.  (5276, 14)
(26212, 14)
BSE/BOM500012 ANDHRA PETROCHEMICALS LTD.  (5222, 14)
(31434, 14)
BSE/BOM500013 ANSAL PROPERTIES & INFRASTRUCTURE LTD.  (4969, 14)
(36403, 14)
BSE/BOM500014 Utique Enterprises Ltd  (5219, 14)
(41622, 14)
BSE/BOM500016 ARUNA HOTELS LTD.  (166, 14)
(41788, 14)
BSE/BOM500020 BOMBAY DYEING & MFG.CO.LTD.  (5276, 14)
(47064, 14)
BSE/BOM500023 Asian Hotels (North) Limited  (4868, 14)
(51932, 14)
BSE/BOM500027 ATUL LTD.  (5252, 14)
(57184, 14)
BSE/BOM500028 ATV PROJECTS INDIA LTD.  (3007, 14)
(60191, 14)
BSE/BOM500029 AUTOLITE (INDIA) LTD.  (5054, 14)
(65245, 14)
BSE/BOM500031 BAJAJ ELECTRICALS LTD.-$  (4988, 14)
(70233, 14)
BSE/BOM500032 Bajaj Hindusthan Sugar Limited  (5097, 14)
(75330, 14)
BSE/BOM500033 FORCE MOTORS LTD.-$  (4854, 14)
(80184, 14)
BSE/BOM500034 Bajaj Finance Limited  (5204, 14)
(85388, 14)
BSE/BOM500038 BALRAMPUR CHINI MILLS LTD.  (5236, 14)
(90624, 14)
BSE/BOM500039 BANCO PRODUCTS (INDIA) LTD.-$  (5176, 14)
(95800, 14)
BSE/BOM500040 CENTURY TEXTILES & INDUSTRIES LTD.  (5276, 14)
(101076, 14)
BSE/BOM500041 BANNARI AMMAN SUGARS LTD.  (4960, 14)
(106036, 14)
BSE/BOM500042 BASF INDIA LTD.  (5275, 14)
(111311, 14)
BSE/BOM500043 BATA INDIA LTD.  (5277, 14)
(116588, 14)
BSE/BOM500048 BEML LTD.  (5276, 14)
(121864, 14)
BSE/BOM500049 BHARAT ELECTRONICS LTD.  (5276, 14)
(127140, 14)
BSE/BOM500052 BHANSALI ENGINEERING POLYMERS LTD.-$  (5094, 14)
(132234, 14)
BSE/BOM500055 Tata Steel Bsl Ltd  (1361, 14)
(133595, 14)
BSE/BOM500058 BIHAR SPONGE IRON LTD.  (4118, 14)
(137713, 14)
BSE/BOM500060 Birla Cable Ltd  (5267, 14)
(142980, 14)
BSE/BOM500067 BLUE STAR LTD.  (5239, 14)
(148219, 14)
BSE/BOM500068 DISA INDIA LTD.  (4788, 14)
(153007, 14)
BSE/BOM500069 BNK CAPITAL MARKETS LTD.  (3758, 14)
(156765, 14)
BSE/BOM500074 BPL LTD.  (5276, 14)
(162041, 14)
BSE/BOM500078 Oriental Aromatics Ltd-$  (5110, 14)
(167151, 14)
BSE/BOM500083 CENTURY EXTRUSIONS LTD.  (4300, 14)
(171451, 14)
BSE/BOM500084 CESC LTD.  (5224, 14)
(176675, 14)
BSE/BOM500085 CHAMBAL FERTILISERS & CHEMICALS LTD.  (5275, 14)
(181950, 14)
BSE/BOM500086 EXIDE INDUSTRIES LTD.  (5274, 14)
(187224, 14)
BSE/BOM500087 CIPLA LTD.  (5276, 14)
(192500, 14)
BSE/BOM500089 DIC INDIA LTD.  (5026, 14)
(197526, 14)
BSE/BOM500092 CRISIL LTD.  (5179, 14)
(202705, 14)
BSE/BOM500093 CG Power and Industrial Solutions Ltd  (5276, 14)
(207981, 14)
BSE/BOM500096 DABUR INDIA LTD.  (5276, 14)
(213257, 14)
BSE/BOM500097 Dalmia Bharat Sugar and Industries Ltd  (4998, 14)
(218255, 14)
BSE/BOM500101 ARVIND LTD.  (5276, 14)
(223531, 14)
BSE/BOM500102 BALLARPUR INDUSTRIES LTD.  (1361, 14)
(224892, 14)
BSE/BOM500103 BHARAT HEAVY ELECTRICALS LTD.  (1361, 14)
(226253, 14)
BSE/BOM500104 HINDUSTAN PETROLEUM CORPORATION LTD.  (5276, 14)
(231529, 14)
BSE/BOM500106 IFCI LTD.  (1361, 14)
(232890, 14)
BSE/BOM500108 MAHANAGAR TELEPHONE NIGAM LTD.  (5277, 14)
(238167, 14)
BSE/BOM500109 MANGALORE REFINERY & PETROCHEMICALS LTD.  (5276, 14)
(243443, 14)
BSE/BOM500110 CHENNAI PETROLEUM CORPORATION LTD.  (5276, 14)
(248719, 14)
BSE/BOM500111 RELIANCE CAPITAL LTD.  (5276, 14)
(253995, 14)
BSE/BOM500112 STATE BANK OF INDIA  (5277, 14)
(259272, 14)
BSE/BOM500113 STEEL AUTHORITY OF INDIA LTD.  (5276, 14)
(264548, 14)
BSE/BOM500114 Titan Company Limited  (5276, 14)
(269824, 14)
BSE/BOM500116 IDBI BANK LTD.  (5277, 14)
(275101, 14)
BSE/BOM500117 DCW LTD.  (5261, 14)
(280362, 14)
BSE/BOM500119 DHAMPUR SUGAR MILLS LTD.  (5199, 14)
(285561, 14)
BSE/BOM500120 DIAMINES & CHEMICALS LTD.-$  (4695, 14)
(290256, 14)
BSE/BOM500123 ELANTAS BECK INDIA LTD.-$  (4950, 14)
(295206, 14)
BSE/BOM500124 DR.REDDY'S LABORATORIES LTD.  (5277, 14)
(300483, 14)
BSE/BOM500125 E.I.D.-PARRY (INDIA) LTD.  (5259, 14)
(305742, 14)
BSE/BOM500126 Procter & Gamble Health Ltd  (5273, 14)
(311015, 14)
BSE/BOM500128 ELECTROSTEEL CASTINGS LTD.  (5265, 14)
(316280, 14)
BSE/BOM500133 ESAB INDIA LTD.  (5253, 14)
(321533, 14)
BSE/BOM500135 EPL Ltd  (5276, 14)
(326809, 14)
BSE/BOM500136 ESTER INDUSTRIES LTD.  (4726, 14)
(331535, 14)
BSE/BOM500142 FGP LTD.  (4110, 14)
(335645, 14)
BSE/BOM500143 PH CAPITAL LTD.  (1870, 14)
(337515, 14)
BSE/BOM500144 FINOLEX CABLES LTD.  (5276, 14)
(342791, 14)
BSE/BOM500147 John Cockerill India Ltd-$  (5178, 14)
(347969, 14)
BSE/BOM500148 UFLEX LTD.  (5260, 14)
(353229, 14)
BSE/BOM500150 FOSECO INDIA LTD.  (5154, 14)
(358383, 14)
BSE/BOM500151 GOLDEN TOBACCO LTD.  (5004, 14)
(363387, 14)
BSE/BOM500153 GANESH BENZOPLAST LTD.  (4690, 14)
(368077, 14)
BSE/BOM500155 GARDEN SILK MILLS LTD.  (5225, 14)
(373302, 14)
BSE/BOM500159 Metroglobal Limited  (3350, 14)
(376652, 14)
BSE/BOM500160 GTL LTD.  (5216, 14)
(381868, 14)
BSE/BOM500163 GODFREY PHILLIPS INDIA LTD.  (5089, 14)
(386957, 14)
BSE/BOM500164 GODREJ INDUSTRIES LTD.  (5152, 14)
(392109, 14)
BSE/BOM500165 KANSAI NEROLAC PAINTS LTD.  (5204, 14)
(397313, 14)
BSE/BOM500166 GOODRICKE GROUP LTD.  (5114, 14)
(402427, 14)
BSE/BOM500168 GOODYEAR INDIA LTD.  (5139, 14)
(407566, 14)
BSE/BOM500170 GTN INDUSTRIES LTD.  (4413, 14)
(411979, 14)
BSE/BOM500171 GHCL LTD.  (5257, 14)
(417236, 14)
BSE/BOM500173 GFL Ltd  (5200, 14)
(422436, 14)
BSE/BOM500174 GUJARAT LEASE FINANCING LTD.  (4310, 14)
(426746, 14)
BSE/BOM500179 HCL INFOSYSTEMS LTD.  (5276, 14)
(432022, 14)
BSE/BOM500180 HDFC Bank Ltd  (5277, 14)
(437299, 14)
BSE/BOM500182 HERO MOTOCORP LTD.  (5276, 14)
(442575, 14)
BSE/BOM500183 HFCL Ltd  (5257, 14)
(447832, 14)
BSE/BOM500184 Himadri Speciality Chemical Ltd  (5071, 14)
(452903, 14)
BSE/BOM500185 HINDUSTAN CONSTRUCTION CO.LTD.  (5252, 14)
(458155, 14)
BSE/BOM500186 HINDUSTAN OIL EXPLORATION CO.LTD.  (5275, 14)
(463430, 14)
BSE/BOM500187 HSIL LTD.  (5113, 14)
(468543, 14)
BSE/BOM500188 HINDUSTAN ZINC LTD.  (5276, 14)
(473819, 14)
BSE/BOM500189 Nxtdigital Ltd  (5248, 14)
(479067, 14)
BSE/BOM500191 HMT LTD.  (5150, 14)
(484217, 14)
BSE/BOM500192 PRAG BOSIMI SYNTHETICS LTD.  (5039, 14)
(489256, 14)
BSE/BOM500193 HLV Ltd  (5276, 14)
(494532, 14)
BSE/BOM500199 I G PETROCHEMICALS LTD.  (5211, 14)
(499743, 14)
BSE/BOM500201 INDIA GLYCOLS LTD.  (5254, 14)
(504997, 14)
BSE/BOM500202 INDIA LEASE DEVELOPMENT LTD.  (3149, 14)
(508146, 14)
BSE/BOM500207 INDO RAMA SYNTHETICS (INDIA) LTD.  (5169, 14)
(513315, 14)
BSE/BOM500209 INFOSYS LTD.  (5277, 14)
(518592, 14)
BSE/BOM500210 INGERSOLL-RAND (INDIA) LTD.  (5275, 14)
(523867, 14)
BSE/BOM500211 INSILCO LTD.  (5269, 14)
(529136, 14)
BSE/BOM500212 INTEGRATED FINANCIAL SERVICES LTD.  (2773, 14)
(531909, 14)
BSE/BOM500213 INTERNATIONAL TRAVEL HOUSE LTD.-$  (5118, 14)
(537027, 14)
BSE/BOM500214 ION EXCHANGE (INDIA) LTD.-$  (5238, 14)
(542265, 14)
BSE/BOM500215 AGRO TECH FOODS LTD.  (5219, 14)
(547484, 14)
BSE/BOM500219 JAIN IRRIGATION SYSTEMS LTD.  (5202, 14)
(552686, 14)
BSE/BOM500220 JASCH INDUSTRIES LTD.  (4268, 14)
(556954, 14)
BSE/BOM500223 JCT LTD.  (5187, 14)
(562141, 14)
BSE/BOM500227 JINDAL POLY FILMS LTD.  (4847, 14)
(566988, 14)
BSE/BOM500228 JSW STEEL LTD.  (5255, 14)
(572243, 14)
BSE/BOM500231 UMANG DAIRIES LTD.  (4840, 14)
(577083, 14)
BSE/BOM500233 KAJARIA CERAMICS LTD.  (5236, 14)
(582319, 14)
BSE/BOM500234 KAKATIYA CEMENT SUGAR & INDUSTRIES LTD.  (5099, 14)
(587418, 14)
BSE/BOM500235 KALYANI STEELS LTD.  (5237, 14)
(592655, 14)
BSE/BOM500236 Kanel Industries Limited  (1662, 14)
(594317, 14)
BSE/BOM500238 WHIRLPOOL OF INDIA LTD.  (5276, 14)
(599593, 14)
BSE/BOM500239 KG DENIM LTD.  (5058, 14)
(604651, 14)
BSE/BOM500240 KINETIC ENGINEERING LTD.  (4978, 14)
(609629, 14)
BSE/BOM500241 KIRLOSKAR BROTHERS LTD.-$  (5135, 14)
(614764, 14)
BSE/BOM500243 Kirloskar Industries Ltd  (5086, 14)
(619850, 14)
BSE/BOM500245 KIRLOSKAR FERROUS INDUSTRIES LTD.  (5156, 14)
(625006, 14)
BSE/BOM500246 ENVAIR ELECTRODYNE LTD.  (3901, 14)
(628907, 14)
BSE/BOM500247 KOTAK MAHINDRA BANK LTD.  (5276, 14)
(634183, 14)
BSE/BOM500248 Krishna Filament Industries Ltd  (2620, 14)
(636803, 14)
BSE/BOM500249 KSB Ltd  (5198, 14)
(642001, 14)
BSE/BOM500250 L.G.BALAKRISHNAN & BROS.LTD.  (4864, 14)
(646865, 14)
BSE/BOM500251 TRENT LTD.  (5275, 14)
(652140, 14)

BSE/BOM500252 LAKSHMI MACHINE WORKS LTD.  (5001, 14)
(657141, 14)
BSE/BOM500253 LIC HOUSING FINANCE LTD.  (1361, 14)
(658502, 14)
BSE/BOM500257 LUPIN LTD.  (1361, 14)
(659863, 14)
BSE/BOM500259 LYKA LABS LTD.  (5261, 14)
(665124, 14)
BSE/BOM500260 The Ramco Cements Limited  (5239, 14)
(670363, 14)
BSE/BOM500264 MAFATLAL INDUSTRIES LTD.-$  (4981, 14)
(675344, 14)
BSE/BOM500265 MAHARASHTRA SEAMLESS LTD.  (5252, 14)
(680596, 14)
BSE/BOM500266 MAHARASHTRA SCOOTERS LTD.  (5189, 14)
(685785, 14)
BSE/BOM500267 MAJESTIC AUTO LTD.-$  (4967, 14)
(690752, 14)
BSE/BOM500268 MANALI PETROCHEMICAL LTD.  (5111, 14)
(695863, 14)
BSE/BOM500271 Max Financial Services Ltd  (5276, 14)
(701139, 14)
BSE/BOM500274 MESCO PHARMACEUTICALS LTD.  (40, 14)
(701179, 14)
BSE/BOM500277 MID INDIA INDUSTRIES LTD.  (377, 14)
(701556, 14)
BSE/BOM500279 MIRC ELECTRONICS LTD.  (1361, 14)
(702917, 14)
BSE/BOM500280 CENTURY ENKA LTD.  (5274, 14)
(708191, 14)
BSE/BOM500284 LORDS CHLORO ALKALI LTD.  (2317, 14)
(710508, 14)
BSE/BOM500285 SPICEJET LTD.  (5269, 14)
(715777, 14)
BSE/BOM500288 MOREPEN LABORATORIES LTD.  (5276, 14)
(721053, 14)
BSE/BOM500290 MRF LTD.  (5273, 14)
(726326, 14)
BSE/BOM500292 HEIDELBERGCEMENT INDIA LTD.  (5240, 14)
(731566, 14)
BSE/BOM500294 NCC Limited  (5134, 14)
(736700, 14)
BSE/BOM500295 Vedanta Limited  (5275, 14)
(741975, 14)
BSE/BOM500296 NAHAR SPINNING MILLS LTD.  (5218, 14)
(747193, 14)
BSE/BOM500298 NATIONAL PEROXIDE LTD.  (5081, 14)
(752274, 14)
BSE/BOM500300 GRASIM INDUSTRIES LTD.  (5276, 14)
(757550, 14)
BSE/BOM500302 PIRAMAL ENTERPRISES LTD.  (1361, 14)
(758911, 14)
BSE/BOM500304 NIIT LTD.  (5250, 14)
(764161, 14)
BSE/BOM500306 JAYKAY ENTERPRISES LTD.  (5167, 14)
(769328, 14)
BSE/BOM500307 NIRLON LTD.  (5265, 14)
(774593, 14)
BSE/BOM500312 Oil and Natural Gas Corporation Ltd  (5276, 14)
(779869, 14)
BSE/BOM500313 OIL COUNTRY TUBULAR LTD.  (5127, 14)
(784996, 14)
BSE/BOM500314 ORIENTAL HOTELS LTD.  (1350, 14)
(786346, 14)
BSE/BOM500317 OSWAL AGRO MILLS LTD.  (2969, 14)
(789315, 14)
BSE/BOM500319 INDIAN SUCROSE LTD.  (3526, 14)
(792841, 14)
BSE/BOM500325 RELIANCE INDUSTRIES LTD.  (5277, 14)
(798118, 14)
BSE/BOM500327 Pil Italica Lifestyle Ltd  (5180, 14)
(803298, 14)
BSE/BOM500329 PENTAMEDIA GRAPHICS LTD.  (5005, 14)
(808303, 14)
BSE/BOM500330 RAYMOND LTD.  (5276, 14)
(813579, 14)
BSE/BOM500331 PIDILITE INDUSTRIES LTD.  (4989, 14)
(818568, 14)
BSE/BOM500333 PIX TRANSMISSIONS LTD.  (5051, 14)
(823619, 14)
BSE/BOM500335 BIRLA CORPORATION LTD.  (5249, 14)
(828868, 14)
BSE/BOM500336 SURYA ROSHNI LTD.  (5194, 14)
(834062, 14)
BSE/BOM500337 PRIME SECURITIES LTD.  (5029, 14)
(839091, 14)
BSE/BOM500338 Prism Johnson Ltd  (5276, 14)
(844367, 14)
BSE/BOM500339 Rain Industries Ltd  (5189, 14)
(849556, 14)
BSE/BOM500343 AMJ Land Holdings Ltd  (5076, 14)
(854632, 14)
BSE/BOM500346 PUNJAB COMMUNICATIONS LTD.-$  (1289, 14)
(855921, 14)
BSE/BOM500350 RSWM LTD.  (4964, 14)
(860885, 14)
BSE/BOM500354 RAJSHREE SUGARS & CHEMICALS LTD.  (5064, 14)
(865949, 14)
BSE/BOM500355 RALLIS INDIA LTD.  (5225, 14)
(871174, 14)
BSE/BOM500356 SHREE RAMA NEWSPRINT LTD.  (5226, 14)
(876400, 14)
BSE/BOM500357 RAMA PAPER MILLS LTD.  (3983, 14)
(880383, 14)
BSE/BOM500358 RAMA PETROCHEMICALS LTD.  (3456, 14)
(883839, 14)
BSE/BOM500360 RAPICUT CARBIDES LTD.  (4383, 14)
(888222, 14)
BSE/BOM500365 Welspun Specialty Solutions Ltd  (4619, 14)
(892841, 14)
BSE/BOM500366 ROLTA INDIA LTD.  (5277, 14)
(898118, 14)
BSE/BOM500367 RUBFILA INTERNATIONAL LTD.  (5026, 14)
(903144, 14)
BSE/BOM500368 RUCHI SOYA INDUSTRIES LTD.  (5158, 14)
(908302, 14)
BSE/BOM500370 SALORA INTERNATIONAL LTD.  (4695, 14)
(912997, 14)
BSE/BOM500378 JINDAL SAW LTD.  (5272, 14)
(918269, 14)
BSE/BOM500380 JK LAKSHMI CEMENT LTD.  (5214, 14)
(923483, 14)
BSE/BOM500387 SHREE CEMENT LTD.  (5224, 14)
(928707, 14)
BSE/BOM500388 SHREE KRISHNA PAPER MILLS & INDUSTRIES LTD.  (1638, 14)
(930345, 14)
BSE/BOM500390 RELIANCE INFRASTRUCTURE LTD.  (5276, 14)
(935621, 14)
BSE/BOM500399 STEELCO GUJARAT LTD.  (4823, 14)
(940444, 14)
BSE/BOM500400 TATA POWER CO.LTD.  (5277, 14)
(945721, 14)
BSE/BOM500402 SPML Infra Limited  (4492, 14)
(950213, 14)
BSE/BOM500403 SUNDRAM FASTENERS LTD.  (5201, 14)
(955414, 14)
BSE/BOM500404 SUNFLAG IRON & STEEL CO.LTD.  (5241, 14)
(960655, 14)
BSE/BOM500405 SUPREME PETROCHEM LTD.  (5274, 14)
(965929, 14)
BSE/BOM500407 SWARAJ ENGINES LTD.  (1360, 14)
(967289, 14)
BSE/BOM500408 TATA ELXSI LTD.  (5276, 14)
(972565, 14)
BSE/BOM500410 ACC LTD.  (5277, 14)
(977842, 14)
BSE/BOM500411 THERMAX LTD.  (5274, 14)
(983116, 14)
BSE/BOM500412 THIRUMALAI CHEMICALS LTD.  (5262, 14)
(988378, 14)
BSE/BOM500413 THOMAS COOK (INDIA) LTD.  (5274, 14)
(993652, 14)
BSE/BOM500414 TIMEX GROUP INDIA LTD.-$  (5089, 14)
(998741, 14)
BSE/BOM500418 TOKYO PLAST INTERNATIONAL LTD.  (4488, 14)
(1003229, 14)
BSE/BOM500420 TORRENT PHARMACEUTICALS LTD.  (5267, 14)
(1008496, 14)
BSE/BOM500422 TRANSCHEM LTD.-$  (5003, 14)
(1013499, 14)
BSE/BOM500425 AMBUJA CEMENTS LTD.  (5276, 14)
(1018775, 14)
BSE/BOM500426 UTL Industries Limited  (1073, 14)
(1019848, 14)
BSE/BOM500429 UNIPHOS ENTERPRISES LTD.  (5177, 14)
(1025025, 14)
BSE/BOM500439 VARDHMAN HOLDINGS LTD.  (4437, 14)
(1029462, 14)
BSE/BOM500440 HINDALCO INDUSTRIES LTD.  (5276, 14)
(1034738, 14)
BSE/BOM500444 WEST COAST PAPER MILLS LTD.  (5262, 14)
(1040000, 14)
BSE/BOM500449 HINDUSTAN ORGANIC CHEMICALS LTD.  (5272, 14)
(1045272, 14)
BSE/BOM500450 MPIL CORPORATION LTD.  (3218, 14)
(1048490, 14)
BSE/BOM500456 PASUPATI ACRYLON LTD.  (5001, 14)
(1053491, 14)
BSE/BOM500458 Kore Foods Ltd  (2321, 14)
(1055812, 14)
BSE/BOM500459 PROCTER & GAMBLE HYGIENE & HEALTH CARE LTD.  (5276, 14)
(1061088, 14)
BSE/BOM500460 MUKAND LTD.  (5217, 14)
(1066305, 14)
BSE/BOM500463 AGC Networks Limited  (5173, 14)
(1071478, 14)
BSE/BOM500464 UCAL FUEL SYSTEMS LTD.  (5234, 14)
(1076712, 14)
BSE/BOM500467 HARRISONS MALAYALAM LTD.  (5214, 14)
(1081926, 14)
BSE/BOM500469 FEDERAL BANK LTD.  (5273, 14)
(1087199, 14)
BSE/BOM500470 TATA STEEL LTD.  (5277, 14)
(1092476, 14)
BSE/BOM500472 SKF India Ltd  (5262, 14)
(1097738, 14)
BSE/BOM500477 ASHOK LEYLAND LTD.  (5276, 14)
(1103014, 14)
BSE/BOM500480 CUMMINS INDIA LTD.  (5276, 14)
(1108290, 14)
BSE/BOM500483 TATA COMMUNICATIONS LTD.  (5275, 14)
(1113565, 14)
BSE/BOM500488 ABBOTT INDIA LTD.  (5268, 14)
(1118833, 14)
BSE/BOM500490 BAJAJ HOLDINGS & INVESTMENT LTD.  (5276, 14)
(1124109, 14)
BSE/BOM500493 BHARAT FORGE LTD.  (5275, 14)
(1129384, 14)
BSE/BOM500495 ESCORTS LTD.  (5276, 14)
(1134660, 14)
BSE/BOM500500 HINDUSTAN MOTORS LTD.  (5257, 14)
(1139917, 14)
BSE/BOM500510 LARSEN & TOUBRO LTD.  (5252, 14)
(1145169, 14)
BSE/BOM500520 MAHINDRA & MAHINDRA LTD.  (5277, 14)
(1150446, 14)
BSE/BOM500530 BOSCH LTD.  (5236, 14)
(1155682, 14)
BSE/BOM500540 PREMIER LTD.  (1223, 14)
(1156905, 14)
BSE/BOM500547 BHARAT PETROLEUM CORPORATION LTD.  (3424, 14)
(1160329, 14)
BSE/BOM500550 SIEMENS LTD.  (5276, 14)
(1165605, 14)
BSE/BOM500570 TATA MOTORS LTD.  (5276, 14)
(1170881, 14)
BSE/BOM500575 VOLTAS LTD.  (5276, 14)
(1176157, 14)
BSE/BOM500620 GREAT EASTERN SHIPPING CO.LTD.  (5245, 14)
(1181402, 14)
BSE/BOM500645 DEEPAK FERTILISERS & PETROCHEMICALS CORPORATION LTD.  (5275, 14)
(1186677, 14)
BSE/BOM500650 EXCEL INDUSTRIES LTD.  (5206, 14)
(1191883, 14)
BSE/BOM500655 GARWARE POLYESTER LTD.  (5241, 14)
(1197124, 14)
BSE/BOM500660 GLAXOSMITHKLINE PHARMACEUTICALS LTD.  (5276, 14)
(1202400, 14)
BSE/BOM500670 GUJARAT NARMADA VALLEY FERTILIZERS & CHEMICALS LTD.  (5276, 14)
(1207676, 14)
BSE/BOM500672 NOVARTIS INDIA LTD.  (5277, 14)
(1212953, 14)
BSE/BOM500674 Sanofi India Ltd  (5269, 14)
(1218222, 14)
BSE/BOM500680 PFIZER LTD.  (5103, 14)
(1223325, 14)
BSE/BOM500690 GUJARAT STATE FERTILIZERS & CHEMICALS LTD.  (5276, 14)
(1228601, 14)
BSE/BOM500696 HINDUSTAN UNILEVER LTD.  (5277, 14)
(1233878, 14)
BSE/BOM500710 Akzo Nobel India Limited  (5275, 14)
(1239153, 14)
BSE/BOM500730 NOCIL LTD.  (5276, 14)
(1244429, 14)
BSE/BOM500770 TATA CHEMICALS LTD.  (5276, 14)
(1249705, 14)
BSE/BOM500777 TAMILNADU PETROPRODUCTS LTD.  (5276, 14)
(1254981, 14)
BSE/BOM500780 ZUARI GLOBAL LTD.  (5256, 14)
(1260237, 14)
BSE/BOM500790 NESTLE INDIA LTD.  (5276, 14)
(1265513, 14)
BSE/BOM500800 Tata Consumer Products Ltd  (5276, 14)
(1270789, 14)

BSE/BOM500820 ASIAN PAINTS LTD.  (5275, 14)
(1276064, 14)
BSE/BOM500825 BRITANNIA INDUSTRIES LTD.  (5273, 14)
(1281337, 14)
BSE/BOM500830 COLGATE-PALMOLIVE (INDIA) LTD.  (1361, 14)
(1282698, 14)
BSE/BOM500840 EIH LTD.  (5276, 14)
(1287974, 14)
BSE/BOM500850 INDIAN HOTELS CO.LTD.  (5276, 14)
(1293250, 14)
BSE/BOM500870 CASTROL INDIA LTD.  (5039, 14)
(1298289, 14)
BSE/BOM500875 ITC LTD.  (5276, 14)
(1303565, 14)
BSE/BOM500877 APOLLO TYRES LTD.  (5276, 14)
(1308841, 14)
BSE/BOM500878 CEAT LTD.  (5248, 14)
(1314089, 14)
BSE/BOM500890 MODI RUBBER LTD.  (2680, 14)
(1316769, 14)
BSE/BOM500940 FINOLEX INDUSTRIES LTD.  (5276, 14)
(1322045, 14)
BSE/BOM501144 PEOPLES INVESTMENTS LTD.  (3, 14)
(1322048, 14)
BSE/BOM501148 DALAL STREET INVESTMENTS LTD.  (1616, 14)
(1323664, 14)
BSE/BOM501150 CENTRUM CAPITAL LTD.  (2812, 14)
(1326476, 14)
BSE/BOM501151 KARTIK INVESTMENTS TRUST LTD.  (62, 14)
(1326538, 14)
BSE/BOM501242 TCI FINANCE LTD.  (4448, 14)
(1330986, 14)

ConnectionError: HTTPSConnectionPool(host='www.quandl.com', port=443): Max retries exceeded with url: /api/v3/datasets/BSE/BOM501295/data?order=asc&start_date=2000-01-01&end_date=2021-03-16 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002C191093F08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

In [ ]:
listedStocks.loc[11]

In [ ]:
dataset.head(5)

In [ ]:
dataset.to_csv('stocks.csv')

In [ ]:
downl = pd.read_csv('stocks.csv')
downl.head()

In [ ]:
downl.loc[downl.BSECode == 500002]

In [3]:
quandl.get('BSE/SI1000', start_date='2000-01-01', end_date='2021-01-21').sort_values(by='Date', ascending=True)

                Open      High       Low     Close
Date
2000-01-03       NaN       NaN       NaN   4260.20
2000-01-04       NaN       NaN       NaN   4554.08
2000-01-05       NaN       NaN       NaN   4342.29
2000-01-06       NaN       NaN       NaN   4160.10
2000-01-07       NaN       NaN       NaN   3828.79
...              ...       ...       ...       ...
2021-01-15  26911.99  26911.99  26292.53  26352.98
2021-01-18  26393.35  26395.61  25860.76  25924.12
2021-01-19  26016.27  26264.17  26016.27  26108.92
2021-01-20  26169.85  26691.29  26169.85  26566.23
2021-01-21  26770.13  26813.06  26299.17  26404.76

[5241 rows x 4 columns]

In [ ]:
# import pandas as pd
# df = pd.read_csv('https://query.data.world/s/jtdkhp453yq6qcimlk2er7hwriwdjl')
# df.head()